config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  devise_for :users
  authenticated :user do
    root to: 'posts#index', as: :authenticated_root
  end
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider', to: 'sessions#create', as: :authenticate
  
  resources :posts
  resources :socials
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/social.rb
class Social < ApplicationRecord
	belongs_to :user
	validates :username, presence: true
  validates :password, presence: true
  validates :media_type, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :socials
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path, status: :see_other
  end

  private
  def post_params
    params.require(:post).permit(:title, :description)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :authenticate_user!
	def create
    auth = request.env['omniauth.auth']
    if auth.present?
      user = User.find_or_initialize_by(provider: auth['provider'], uid: auth['uid'])
      user.name = auth['info']['name']
      user.email = auth['info']['email']
      user.save
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in successfully'
    else
      redirect_to root_url, alert: 'Authentication failed. Please try again.'
    end
  end
end

app/controllers/socials_controller.rb
class SocialsController < ApplicationController
  before_action :authenticate_user!
  def index
    @socials = Social.all
  end
  
  def show
    @social = Social.find(params[:id])
  end

  def new
    @social = Social.new
  end

  def create
    @social = Social.new(social_params)
    password = params[:social][:password]
    if @social.save
      redirect_to @social, notice: 'Social was successfully created.'
    else
      render :new
    end
  end

  def edit
    @social = Social.find(params[:id])
  end

  def update
    @social = Social.find(params[:id])
    if @social.update(social_params)
      redirect_to @social
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @social = Social.find(params[:id])
    @social.destroy
    redirect_to root_path, status: :see_other
  end

  private
  def social_params
    params.require(:social).permit(:username, :password, :media_type,:user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/socials_helper.rb
module SocialsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <%= link_to "SocialPost", root_path, class: "navbar-brand" %>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active", "aria-current": "page" %>
        </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Settings
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile Create", new_social_path, class: "nav-link active", "aria-current": "page" %></li>
          <li><%= link_to "Facebook", "/auth/facebook", class: "nav-link active", "aria-current": "page" %> </li>
        </ul>
      </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogpostProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <body>
    <%= render "layouts/header" %>
    <%= yield %>

    <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to "Edit profile", edit_user_registration_path, class: "navbar-link" %> | <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-link" %>

    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: "navbar-link"  %> |
      <%= link_to "Login", new_user_session_path, class: "navbar-link"  %>
    <% end %>
    </p>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% post.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :description %><br>
      <%= form.text_area :description %><br>
      <% post.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul>
  <% @posts.each do |post| %>
    <li>
        <%= post.title %>
    </li>
  <% end %>
</ul>

<%= link_to "New Post", new_post_path, class: "btn btn-primary" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.description %></p>

<ul>
  <li><%= link_to "Edit", edit_post_path(@post) %></li>
</ul>

app/views/socials/_form.html.erb
<center>
	<%= form_with model: @social do |form| %>
		<div>
			<%= form.label :username %><br>
			<%= form.text_field :username %>
			<% @social.errors.full_messages_for(:username).each do |message| %>
				<div><%= message %></div>
			<% end %>
		</div>

		<div>
			<%= form.label :password %><br>
			<%= form.text_field :password %><br>
			<% @social.errors.full_messages_for(:password).each do |message| %>
				<div><%= message %></div>
			<% end %><br>
		</div>

		<div class="form-group">
		<%= form.label :media_type, "Social media Platform" %><br>
		<%= form.select :media_type, options_for_select(["Instagram","LinkedIn","Twitter"]), { prompt: "Select Platform" }%><br>
			<% @social.errors.full_messages_for(:media_type).each do |message| %>
				<div><%= message %></div>
			<% end %>
		</div>

		<div>
			<%= form.hidden_field :user_id, value: current_user.id %>
		</div>

		<div>
			<br>
			<%= form.submit "Create Profile" %>
		</div>
	<% end %>

</center>

app/views/socials/edit.html.erb
<center><h2>Edit Profile</h2></center>
<%= render "form", social: @social %>

app/views/socials/index.html.erb
<h1>Socials#index</h1>
<p>Find me in app/views/socials/index.html.erb</p>

app/views/socials/new.html.erb
<center><h2>New Profile</h2></center>
<%= render 'form', social: @social %>

app/views/socials/show.html.erb
<h1><%= @social.username %></h1>

<p><%= @social.password %></p>

<ul>
  <li><%= link_to "Edit", edit_social_path(@social) %></li>
</ul>